cursodjango/aperitivos/urls.py
from django.urls import path

from cursodjango.aperitivos.views import video

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video')
]

cursodjango/base/urls.py
from django.urls import path

from cursodjango.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

cursodjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursodjango.base.urls')),
    path('aperitivos/', include('cursodjango.aperitivos.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

cursodjango/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User Class
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

cursodjango/aperitivos/views.py
from django.shortcuts import render


def video(request, slug):
    return render(request, 'aperitivos/video.html')

cursodjango/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

cursodjango/aperitivos/templates/aperitivos/video.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Curso Django App</title>

    <meta name="description" content="Curso Django">
    <meta name="author" content="Jonatas Silva">

      <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="{% url 'base:home' %}">Curso Django</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">


                </ul>

              </div>
            </nav>

    <div class="container">
	<div class="row">
		<div class="col-md-12">

			<h1 class="mt-5 mb-3">Video Aperitivo: Motivação</h1>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/gtgI7PC_TJk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>
	</div>
</div>

    <footer class="main_footer mt-5 pt-4 text-light">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3>Entre em contato</h3>
                    <address>
                        +55 (86) 9 99971-9767
                        <br />
                        <a class="text-light" href="mailto:jonatas.iw@gmail.com">jonatas.iw@gmail.com</a>
                    </address>
                </div>
            </div>
        </div>
        <div class="rights pb-4 ">
            <div class="container">
                <div class="row">
                    <div class="col">
                        {% now 'Y' %} Curso Django Todos dideitos reservados
                    </div>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

cursodjango/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Curso Django App</title>

    <meta name="description" content="Curso Django">
    <meta name="author" content="Jonatas Silva">

      <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="{% url 'base:home' %}">Curso Django</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">


                </ul>

              </div>
            </nav>

    <div class="container">
	<div class="row">
		<div class="col-md-12">

			<div class="jumbotron">
				<h2>
					Curso Django
				</h2>
				<p>
					Em breve mais informacoes. Nao perca <a href="https://novatec.com.br/livros/pythonedjango/" target="_blank">Django</a>
				</p>

			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre a autora
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img class="img-thumbnail float-left mr-3" alt="Pessoa do autor" src="{% static 'img/img.jpg' %}" >
							    Biografia de Fernando Pessoa Fernando Pessoa (1888-1935) foi um dos mais importantes poetas
                                da língua portuguesa e figura central do Modernismo português. Poeta lírico e nacionalista
                                cultivou uma poesia voltada aos temas tradicionais de Portugal e ao seu lirismo saudosista,
                                que expressa reflexões sobre seu “eu profundo”, suas inquietações, sua solidão e seu tédio.
                                Fernando Pessoa foi vários poetas ao mesmo tempo, criou heterônimos, poetas com personalidades
                                próprias que escreveram sua poesia.
                            </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

    <footer class="main_footer mt-5 pt-4 text-light">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3>Entre em contato</h3>
                    <address>
                        +55 (86) 9 99971-9767
                        <br />
                        <a class="text-light" href="mailto:jonatas.iw@gmail.com">jonatas.iw@gmail.com</a>
                    </address>
                </div>
            </div>
        </div>
        <div class="rights pb-4 ">
            <div class="container">
                <div class="row">
                    <div class="col">
                        {% now 'Y' %} Curso Django Todos dideitos reservados
                    </div>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>